### PR TITLE
TASK: Tracking should only be enabled in the production context

### PR DESCRIPTION
**Pull request by rolandschuetz**

### CODE REVIEW

**Comment by kdambekalns** [comment]
TBH I'd do this different (and sorry for not having done this way earlier)… I'd only emit the tracking code if the tracking ID is set, and then it'd be up to the developer to define the tracking code only for Production. That way you could enable it for other contexts (or even use a testing ID for development) as needed without having to override the Fusion code.

What do you think?

**Comment by aertmann** [comment]
I've previously done what @kdambekalns is suggesting myself as this is a bit limiting. However it might not be a bad default and the other thing can still be achieved by changing the @if condition.

**Comment by rolandschuetz** [comment]
If users configure the Google Analytics via the backend this approach wouldn't work. It would only work by settings the ID in the Production/Settings.yaml. So I would still merge the pull request, but as you like...

**Comment by rolandschuetz** [comment]
Ok, I closed the pull request.

**Comment by kitsunet** [comment]
I don't necessarily say we need to close it, but we need to be careful as this could easily become a breaking change :)

**Comment by kdambekalns** [comment]
> If users configure the Google Analytics via the backend this approach wouldn't work.

Ah, good point! Then it makes sense. And of course @aertmann is right, both ways are possible using a one-line Fusion change.

So, I dare to reopen and we just fix the check for the live context…

**Comment by kdambekalns** [comment]
@kitsunet Do you have a working solution at hand for the check? In PHP I'd use `ApplicationContext->isProduction()`…

**Comment by kitsunet** [comment]
New Setting `enableTracking` and true it only in `Configuration/Production/Settings.yaml`?
I think we should *strongly* advice against using the context in anything directly.

**Comment by kitsunet** [comment]
Always setting flag. We hsould in fact declare context non api IMHO.

**Comment by kdambekalns** [comment]
Ping… @rolandschuetz - interested in taking care?

**Comment by rolandschuetz** [comment]
I have implemented this as a new pull request:
https://github.com/neos/neos-googleanalytics/pull/49

**Pull request closed without merging**
