### PR TITLE
Reverted #66fdecd

### PR DESCRIPTION
**Pull request by paavo**

### CODE REVIEW

**Comment by dlubitz** [comment]
See: https://github.com/neos/neos-googleanalytics/pull/79

Looks fine!

**Comment by paavo** [comment]
@Sebobo somehow compsoser.json for 3.2 got updated and requires neos 7 now 🙈 

` neos/googleanalytics 3.2.4 requires neos/neos ^7.0`

**Comment by dlubitz** [comment]
Oh... It seems to be just a wrong reference for the tag.

**Comment by Sebobo** [comment]
🤦  yes sorry. 3.2.5 released...

**Comment by Sebobo** [comment]
Prime example how a simple small change can create 100 headaches...

**Pull request merged**
