### PR TITLE
TASK: Comply with NodeTypes schema

### PR DESCRIPTION
**Pull request by hhoechtl**
Related: NEOS-1529

### CODE REVIEW

**Comment by hhoechtl** [comment]
Also related to https://github.com/neos/neos-development-collection/pull/692

**Comment by aertmann** [comment]
guess this won't be breaking, but not entirely sure

**Comment by hhoechtl** [comment]
@aertmann want another reviewer, or merge it? People are confused by the backend errors.

**Comment by mficzel** [comment]
As far as i remember the boolean syntax for superTypes works only in Neos 2.0+ ... so i would consider this breaking and also raise the required Neos version.

**Comment by kdambekalns** [comment]
Neos 2.0+ is fine, but if the package doesn't require that it should be adjusted anyway. And it was this very package that made us realise we need a way to "undo" supertypes, so I really think the change as such is fine.

**Comment by aertmann** [comment]
@kdambekalns: wasn't it the seo package that made us realize that?

anyway thinking about it again, this change should be fine as you cannot unset the old values anyway so it shouldn't be breaking

**Comment by kdambekalns** [comment]
Hah, true. It was the seo package, indeed.

**Comment by aertmann** [comment]
argh crap needs to go into the `1.0` branch

**Pull request merged**
