### PR TITLE
TASK: Update file headers, apply PSR-2 and PSR-4

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by gerhard-boden** [comment]
Can you commit the changes as "moved files" rather than "deleted and recreated"? If we push it like this, is the history still intact?

**Comment by kdambekalns** [comment]
No I cannot. Actually, git doesn't even track files… So those "files" seem to be over the rename detection threshold.

Hm. Wait a minute…

**Comment by kdambekalns** [comment]
There you go :)

**Comment by gerhard-boden** [comment]
@kdambekalns Thanks for checking! When I look at the changes on GH, it still looks like newly created and deleted files.
image

Is it just the GH preview?

**Comment by kdambekalns** [comment]
Yes, because it shows the "diff over all commits". Check https://github.com/neos/neos-googleanalytics/pull/14/commits/8e0cc65445ffa91c550f751a3596cf084a63d78c to see just the PSR-4 commit. Or `git log -p`:

```
commit 8e0cc65445ffa91c550f751a3596cf084a63d78c
Author: Karsten Dambekalns <karsten@dambekalns.de>
Date:   Tue Jan 17 15:47:52 2017 +0100

    TASK: Apply PSR-4 to package

diff --git a/Classes/TYPO3/Neos/GoogleAnalytics/Controller/ConfigurationController.php b/Classes/Controller/ConfigurationController.php
similarity index 100%
rename from Classes/TYPO3/Neos/GoogleAnalytics/Controller/ConfigurationController.php
rename to Classes/Controller/ConfigurationController.php
diff --git a/Classes/TYPO3/Neos/GoogleAnalytics/Domain/Dto/DataResult.php b/Classes/Domain/Dto/DataResult.php
similarity index 100%
rename from Classes/TYPO3/Neos/GoogleAnalytics/Domain/Dto/DataResult.php
rename to Classes/Domain/Dto/DataResult.php
…
```

**Pull request merged**
