### PR TITLE
!!! FEATURE: Adjust to Neos 3.0

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
One caveat: Lacks a PostgreSQL migration right now.

**Comment by aertmann** [comment]
Hey @kdambekalns 

Wasn't allowed to push to your forks master branch, so created a PR against it instead https://github.com/kdambekalns/neos-googleanalytics/pull/1

With that it should be good to go except the lacking migration, do you plan taking care of that?

**Comment by kdambekalns** [comment]
Yes, I'll add the PostgreSQL migration.

Funny about the PR to the PR. You should be able to edit stuff, since:
edits-allowed

**Comment by kdambekalns** [comment]
PR is merged

**Comment by kdambekalns** [comment]
And done with the PostgreSQL migration(s)…

**Comment by aertmann** [comment]
@kdambekalns: yeah I've had issues with the multiple times, think it's very sensitive as to how it's done and certainly doesn't work in most cases even though it's a simple fast-forward push directly to the branch.. also not sure if there's any difference from it being the master branch or not..

**Pull request merged**
